- name: Simple Playbook
  hosts: ec2
  vars:
    ansible_python_interpreter: /usr/bin/python3
  remote_user: ubuntu
  tasks:
  - name: Touch files with an optional mode
    ansible.builtin.file:
      dest: "{{ item.path }}"
      state: touch
      mode: "{{ item.mode | default(omit) }}"
    loop:
      - path: /tmp/foo
      - path: /tmp/bar
      - path: /tmp/baz
        mode: "0444"