- name: Simple Playbook
  hosts: ec2
  vars:
    ansible_python_interpreter: /usr/bin/python3
  remote_user: ubuntu
  -tasks:
   - name: Set a hostname
     ansible.builtin.hostname:
       name: ansible_test
