- name: Simple Playbook
  hosts: ec2
  vars:
    ansible_python_interpreter: /usr/bin/python3
  remote_user: ubuntu
  tasks:
   - name: Update and upgrade apt packages
     become: yes
     apt:
       upgrade: yes
       update_cache: yes
   - name: Install Open-JDK
     become: yes
     apt:
       name: openjdk-8-jdk
